version: '3.3'
services:
  cueo-backend:
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/api:/app:rw
    network_mode: "host"

  cueo-alerts:
    build:
      context: alerts-api
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/alerts-api:/code:rw
    network_mode: "host"

  cueo-search:
    build:
      context: search-api
      dockerfile: Dockerfile
    environment:
      - SEARCH_POSTGRES_DB_HOST=SEARCH_POSTGRES_DB_HOST
      - SEARCH_POSTGRES_DB_SCHEMA=SEARCH_POSTGRES_DB_SCHEMA
      - SEARCH_POSTGRES_DB_USERNAME=SEARCH_POSTGRES_DB_USERNAME
      - SEARCH_POSTGRES_DB_PASSWORD=SEARCH_POSTGRES_DB_PASSWORD
      - SEARCH_POSTGRES_DB_HOST=SEARCH_POSTGRES_DB_HOST
      - SEARCH_POSTGRES_DB_PORT=SEARCH_POSTGRES_DB_PORT
    volumes:
      - ${PWD}/search-api:/code:rw
    network_mode: "host"

  cueo-frontend:
    build:
      context: ui
      dockerfile: Dockerfile
    # volumes:
    #   - /frontend:/app
    network_mode: "host"

  postgresql-cue:
    image: postgres:13
    environment:
      - PGDATA=/pg_data
      - POSTGRES_DB=cue_observe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/pg_data
    network_mode: "host"


networks:
  external-network:
    external:
      name: nginx-web
  cue-network:
    internal: true

volumes:
  pgdata: