version: '3.3'
services:
  cueo-backend:
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/api:/app:rw
    network_mode: "host"

  cueo-alerts:
    build:
      context: alerts-api
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/alerts-api:/code:rw
    network_mode: "host"

  cueo-frontend:
    build:
      context: ui
      dockerfile: Dockerfile
    volumes:
      - /frontend:/app
    network_mode: "host"

  postgresql-cue:
    image: postgres:13
    environment:
      - PGDATA=/pg_data
      - POSTGRES_DB=cue_observe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/pg_data
    network_mode: "host"


networks:
  external-network:
    external:
      name: nginx-web
  cue-network:
    internal: true

volumes:
  pgdata: