version: '3.3'
services:
  cueo-backend:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      API_URL: ${API_URL}
      ALERT_API_URL: ${ALERT_API_URL}
      POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB_SCHEMA: ${POSTGRES_DB_SCHEMA}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      IS_AUTHENTICATION_REQUIRED: ${IS_AUTHENTICATION_REQUIRED}
      REDIS_BROKER_URL:
    volumes:
      - sqliteDB:/code/db:rw

  cueo-alerts:
    build:
      context: alerts-api
      dockerfile: Dockerfile

  cueo-frontend:
    build:
      context: ui
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - cueo-backend
    command:
      bash -c "./etc/nginx/conf.d/nginx-entrypoint.sh && nginx -g 'daemon off;'"
    ports:
      - "3000:3000"
    links:
      - "cueo-alerts"
      - "cueo-backend"
      - "cueo-redis"
      - "cueo-postgresql"

  cueo-postgresql:
    image: postgres:13
    environment:
      - PGDATA=/pg_data
      - POSTGRES_DB=cue_observe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/pg_data
    network_mode: "host"


  cueo-redis:
    image: redis

volumes:
  sqliteDB:


    