version: '3.3'
services:
  cueo-backend:
    image: cuebook/cue-observe-backend:latest
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      API_URL: ${API_URL}
      ALERT_API_URL: ${ALERT_API_URL}
      POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB_SCHEMA: ${POSTGRES_DB_SCHEMA}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      IS_AUTHENTICATION_REQUIRED: ${IS_AUTHENTICATION_REQUIRED}
    volumes:
      - sqliteDB:/code/db:rw
    network_mode: "host"

  cueo-alerts:
    image: cuebook/cue-observe-alerts:latest
    network_mode: "host"

  cueo-search:
    build:
      context: search-api
      dockerfile: Dockerfile
    environment:
      - SEARCH_POSTGRES_DB_HOST
      - SEARCH_POSTGRES_DB_SCHEMA
      - SEARCH_POSTGRES_DB_USERNAME
      - SEARCH_POSTGRES_DB_PASSWORD
      - SEARCH_POSTGRES_DB_PORT
    volumes:
      - ${PWD}/search-api:/code:rw
    network_mode: "host"

  cueo-frontend:
    image: cuebook/cue-observe-frontend:latest
    depends_on:
      - cueo-backend
    network_mode: "host"

  cueo-redis:
    image: redis
    network_mode: "host"

volumes:
  sqliteDB:
    